### ISSUE TITLE
When an error occur decoding opus, the headers are sent out of order and the app crashes.

### ISSUE THREAD

**Issue by andrenatal** [mozilla/speech-proxy#33]
```
Reading profile opusdec.profile
Error: line 21 in opusdec.profile is invalid
error opusdec close
_http_outgoing.js:504
    throw new Error('Can\'t set headers after they are sent.');
mandando header 200
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at Request._callback (/home/andre/voicefill/speech-proxy/server.js:174:9)
    at Request.self.callback (/home/andre/voicefill/speech-proxy/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/andre/voicefill/speech-proxy/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/andre/voicefill/speech-proxy/node_modules/request/request.js:1091:12)

Process finished with exit code 1
```

**Comment by andrenatal** [comment]
fixed by https://github.com/mozilla/speech-proxy/pull/36
